<?php// Jotform retrun data using webhook
$result = $_REQUEST['rawRequest'];
/*response data */
$obj = json_decode($result, true);if(isset($_POST["submissionID"])){$submission_id=$_POST["submissionID"];$slug=$obj["event_id"];$slug=explode('_', $slug);$formID=$slug[1];/*phonenumber = q130_phoneNumber= this is your jotform field name*/$phone_number_code=$obj["q130_phoneNumber"]['area'];$phone_number=$obj["q130_phoneNumber"]['phone'];/*phonenumber*//*whatsapp phonenumber*/$whatsapp_number=$obj["q138_whatsappNumber138"];/*whatsapp phonenumber*/

//email$email=$obj["q6_email"];
//name$name=$obj["q96_name96"];

/*payment methods*/$checkthe=$obj["q8_checkThe"];$checkpayment=array();foreach ($checkthe as $key => $value) { $checkpayment[]=$value;}$checkthepayment= implode(" / ", $checkpayment);
/*payment methods*/$producttitle=$obj["q60_productTitle"];/*Type of listing */if($obj["q182_typeOf"] == "Sale"){$checkthe="<span>Accepted Payment Methods:</span></strong><em>  ".$checkthepayment;$productprice=$obj["q25_yourAsking25"]; }else
{$checkthe="<span>Tip (money the owner is willing to give to whoever takes this item)</span></strong><em> : ".$obj['q183_tip']." NIS";$productprice=0.00;}
/*Type of listing */
//product Description$Description=$obj["q61_productDescription61"];
//Category$whichCategory=$obj["q139_whichCategory"];
//room$room=$obj["q161_inWhich"];$productarray=array();  
//unique id$sku1=$obj['q177_uniqueid'];
//product1$variants=array('0' =>array("price" =>$productprice,"sku" =>'Item-'.$sku1));$images=array();$temp_upload=$obj["temp_upload"];if(!empty($temp_upload)){
/*upload Imaeg*/   foreach ($temp_upload as $keys => $values) {if($keys == "q26_uploadA26"){$uploadimage=$values;foreach ($uploadimage as $key => $value) {$image="Jot_From_image_path_goes_here".$formID."/".$submission_id."/".$value;$bin = file_get_contents($image);$b64 = base64_encode($bin);$images[$key]=array("attachment"=>$b64,"filename"=> "Appliances.jpg");/*upload Imaeg*/ }}}

/*upload Photo 1*/if(!empty($obj['q88_takeA88'])){$imagescount=count($images);$typedata = explode(',', $obj['q88_takeA88']);$images[$imagescount]=array("attachment"=>$typedata[1],"filename"=> "Appliances.jpg");  }
/*upload Photo 2*/if(!empty($obj['q91_takeAn91'])){$imagescount=count($images);$typedata = explode(',', $obj['q91_takeAn91']);$images[$imagescount]=array("attachment"=>$typedata[1],"filename"=> "Appliances.jpg");  }
if(!empty($wpphonenumber)){ //select whatsapp number$wp="<a href='https://wa.me/".$wpphonenumber."?text=your-text-message-goes-here'><button>WhatsApp Seller</button></a>";$wpd="<a href='https://wa.me/".$wpphonenumber."?text=your-text-message-goes-here'>By WhatsApp</a>";}
else{//not select whatsapp number    $wp="";    $wpd="";}
$wps="<div class='btn-group'>".$wp."    <a href='mailto:".$email."?subject=Hi%20".$name."%20I%20am%20interested%20in%20the%20".$producttitle."&amp;body=Hi%20".$name."%20I%20am%20interested%20in%20the%20".$producttitle."%20you%20are%20selling%20on%20TheJerusalemMarket.com'><button>Email Seller</button></a></div><div class='btn-group'></div><div class='btn-group'></div>";if(!empty($q132_input132)){ //make an offer select $mk="<div class='dropdown'><button class='dropbtn'>MAKE AN OFFER</button><div class='dropdown-content'><a href='mailto:".$email."?subject=Hi%20".$name."%20I%20am%20interested%20in%20the%20".$producttitle."&amp;body=Hi%20".$name."%20I%20am%20interested%20in%20the%20".$producttitle."%20you%20are%20selling%20on%20TheJerusalemMarket.com%20Would%20you%20be%20willing%20to%20give%20it%20to%20me%20for%20₪'>By Email</a>".$wpd."</div></div><p>The seller is willing to consider a reasonable offer.</p>";}
else{//make an offer not select$mk="";}
//Neighborhood$whichneighborhood=$obj["q160_whichNeighborhood160"];$whichneighborhoodarray=array();$whichneighborhoodarray[0]=$whichneighborhood;if($obj["q182_typeOf"] == "Sale"){  $whichneighborhoodarray[1]=$whichCategory;    
  $whichneighborhoodarray[2]=$room;
  $premiumListing27=$obj["q27_premiumListing27"];
if($premiumListing27 != 'No thanks.' && !empty($premiumListing27))
 {//premiumListing  $whichneighborhoodarray[3]='featured listings 1';  $whichneighborhoodarray[4]='featured listings 2';}
}
else{$whichneighborhoodarray[1]='Give Away';}
$productarray=array("title" => $producttitle,                    "body_html" => $Description."<br><br> ".$mk. " <p>--------------------------------------</p><h3><span><strong>Seller Information</strong></span></h3><p><strong><span>Name: </span></strong><em>".$name."</em><em><span> </span></em></p><p><strong><span>Contact Info:</span></strong><em> (".$phonenumbercode.") ".$phonenumber." ".$email."<br></em></p><p><strong> ".$checkthe." <em><span> </span></em></em></p><p><strong><span>Item Location:</span></strong> ".$whichneighborhood."</p>".$wps,                    "template_suffix" => "requires-contact",                     "vendor" => $name,                    "tags"=>$whichneighborhoodarray,                    "variants"=>$variants,                    "images"=>$images                    );
$handle=array();
$array = array("product"=>$productarray);$url = "https://35e0466335d7fba2b4863aa691431e26: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@You-Shop_Path-Goes_here/admin/api/2021-04/products.json";$curl = curl_init();curl_setopt($curl, CURLOPT_URL, $url);curl_setopt($curl, CURLOPT_HTTPHEADER, array('Content-Type: application/json'));curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "POST");curl_setopt($curl, CURLOPT_POSTFIELDS, json_encode($array));curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);$response = curl_exec ($curl);$response = json_decode($response, true);
//product name link$handle[0]=$response['product']['handle'];//file_put_contents('test1.txt', print_r($response, true));

curl_close ($curl);//product2$producttitle14=$obj["q14_productTitle14"];$yourasking34=$obj["q34_yourAsking34"];$productdescription63=$obj["q63_productDescription63"];
if(isset($producttitle14) && !empty($producttitle14)){$whichneighborhood=$obj["q160_whichNeighborhood160"];$whichCategory=$obj["q142_whichCategory142"];$room=$obj["q162_inWhich162"];$whichneighborhoodarray=array();$whichneighborhoodarray[0]=$whichneighborhood;$producttitle=$obj["q14_productTitle14"];if($obj["q182_typeOf"] == "Sale"){   $productprice=$obj["q34_yourAsking34"];   $checkthe="<span>Accepted Payment Methods:</span></strong><em>  ".$checkthepayment;   $whichneighborhoodarray[1]=$whichCategory;       $whichneighborhoodarray[2]=$room;    $premiumListing35=$obj["q35_premiumListing35"];  if($premiumListing35 != 'No thanks.' && !empty($q35_premiumListing35))  {    $whichneighborhoodarray[3]='featured listings 1';      $whichneighborhoodarray[4]='featured listings 2';  }}
else{    $productprice=0.00;    $whichneighborhoodarray[1]='Give Away';    $checkthe="<span>Tip (money the owner is willing to give to whoever takes this item)</span></strong><em> : ".$obj['q184_tip184']." NIS";}
$Description=$obj["q63_productDescription63"];$sku2=$obj['q178_uniqueid2'];$variants=array('0' =>array("price" =>$productprice,"sku" =>'Item-'.$sku2));
/*upload Imaeg*/ $images=array();if(!empty($temp_upload)){/*upload Imaeg*/   foreach ($temp_upload as $keys => $values) {if($keys == "q33_uploadA33"){$uploadimage=$values;foreach ($uploadimage as $key => $value) {$image="https://www.jotform.com/uploads/".$formID."/".$submission_id."/".$value;$bin = file_get_contents($image);$b64 = base64_encode($bin);$images[$key]=array("attachment"=>$b64,"filename"=> "Appliances.jpg");//fwrite($fh, 'datav'.$b64);  }}}}
/*upload Imaeg*/ 
/*upload Photo*/
if(!empty($obj['q117_takeA117'])){
$imagescount=count($images);$typedata = explode(',', $obj['q117_takeA117']);$images[$imagescount]=array("attachment"=>$typedata[1],"filename"=> "Appliances.jpg");  }
if(!empty($obj['q117_takeA117'])){
$imagescount=count($images);$typedata = explode(',', $obj['q117_takeA117']);$images[$imagescount]=array("attachment"=>$typedata[1],"filename"=> "Appliances.jpg");  }
if(!empty($obj['q92_takeAn'])){$imagescount=count($images);$typedata = explode(',', $obj['q92_takeAn']);
$images[$imagescount]=array("attachment"=>$typedata[1],"filename"=> "Appliances.jpg");  }
if(!empty($obj['q99_takeAn99'])){$imagescount=count($images);$typedata = explode(',', $obj['q99_takeAn99']);$images[$imagescount]=array("attachment"=>$typedata[1],"filename"=> "Appliances.jpg");  }
if(!empty($obj['q100_takeAn100'])){$imagescount=count($images);$typedata = explode(',', $obj['q100_takeAn100']);$images[$imagescount]=array("attachment"=>$typedata[1],"filename"=> "Appliances.jpg");  }
if(!empty($obj['q101_takeAn101'])){$imagescount=count($images);$typedata = explode(',', $obj['q101_takeAn101']);$images[$imagescount]=array("attachment"=>$typedata[1],"filename"=> "Appliances.jpg");  }/*upload Photo*/
$productarray=array("title" => $producttitle,                    "body_html" => $Description."<br><br> ".$mk. " <p>--------------------------------------</p><h3><span><strong>Seller Information</strong></span></h3><p><strong><span>Name: </span></strong><em>".$name."</em><em><span> </span></em></p><p><strong><span>Contact Info:</span></strong><em> (".$phonenumbercode.") ".$phonenumber." ".$email."<br></em></p><p><strong> ".$checkthe." <em><span> </span></em></em></p><p><strong><span>Item Location:</span></strong> ".$whichneighborhood." </p>".$wps,                    "template_suffix" => "requires-contact",                    "vendor" => $name,                     "tags"=>$whichneighborhoodarray,                    "variants"=>$variants,                    "images"=>$images                    );$array = array("product"=>$productarray);$url = "https://35e0466335d7fba2b4863aa691431e26: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@Your-shopify-url-goes-here/admin/api/2021-04/products.json";$curl = curl_init();curl_setopt($curl, CURLOPT_URL, $url);curl_setopt($curl, CURLOPT_HTTPHEADER, array('Content-Type: application/json'));curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "POST");curl_setopt($curl, CURLOPT_POSTFIELDS, json_encode($array));curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);$response = curl_exec ($curl);$response = json_decode($response, true);//product name link$handle[1]=$response['product']['handle'];curl_close ($curl);}

//product3$producttitle64=$obj["q64_productTitle64"];$yourasking42=$obj["q42_yourAsking42"];$productdescription66=$obj["q66_productDescription66"];if(isset($producttitle64) && !empty($producttitle64)){$whichneighborhood=$obj["q160_whichNeighborhood160"];$whichCategory=$obj["q143_whichCategory143"];$room=$obj["q163_inWhich163"];$whichneighborhoodarray=array();$whichneighborhoodarray[0]=$whichneighborhood;$producttitle=$obj["q64_productTitle64"];if($obj["q182_typeOf"] == "Sale"){   $productprice=$obj["q42_yourAsking42"];   $checkthe="<span>Accepted Payment Methods:</span></strong><em>  ".$checkthepayment;   $whichneighborhoodarray[1]=$whichCategory;       $whichneighborhoodarray[2]=$room;    $premiumListing43=$obj["q43_premiumListing43"];  if($premiumListing43 != 'No thanks.' && !empty($premiumListing43)) {    $whichneighborhoodarray[3]='featured listings 1';      $whichneighborhoodarray[4]='featured listings 2'; }}else{    $productprice=0;    $whichneighborhoodarray[1]='Give Away';    $checkthe="<span>Tip (money the owner is willing to give to whoever takes this item)</span></strong><em> : ".$obj['q184_tip184']." NIS";}$Description=$obj["q66_productDescription66"];$sku3=$obj['q179_uniqueid3'];$variants=array('0' =>array("price" =>$productprice,"sku" =>'Item-'.$sku3));
/*upload Imaeg*/ $images=array();if(!empty($temp_upload)){
/*upload Imaeg*/   foreach ($temp_upload as $keys => $values) {if($keys == "q41_uploadA41"){$uploadimage=$values;foreach ($uploadimage as $key => $value) {$image="https://www.jotform.com/uploads/".$formID."/".$submission_id."/".$value;$bin = file_get_contents($image);$b64 = base64_encode($bin);$images[$key]=array("attachment"=>$b64,"filename"=> "Appliances.jpg");}
}}}/*upload Imaeg*/ 
/*upload Photo*/if(!empty($obj['q98_takeA'])){$imagescount=count($images);$typedata = explode(',', $obj['q98_takeA']);$images[$imagescount]=array("attachment"=>$typedata[1],"filename"=> "Appliances.jpg");  }
if(!empty($obj['q102_takeAn102'])){$imagescount=count($images);$typedata = explode(',', $obj['q102_takeAn102']);$images[$imagescount]=array("attachment"=>$typedata[1],"filename"=> "Appliances.jpg");  }
/*upload Photo*/$productarray=array("title" => $producttitle,                    "body_html" => $Description."<br><br> ".$mk. " <p>--------------------------------------</p><h3><span><strong>Seller Information</strong></span></h3><p><strong><span>Name: </span></strong><em>".$name."</em><em><span> </span></em></p><p><strong><span>Contact Info:</span></strong><em> (".$phonenumbercode.") ".$phonenumber." ".$email."<br></em></p><p><strong> ".$checkthe." <em><span> </span></em></em></p><p><strong><span>Item Location:</span></strong> ".$whichneighborhood." </p>".$wps,                    "template_suffix" => "requires-contact",                    "vendor" => $name,                    "tags"=>$whichneighborhoodarray,                    "variants"=>$variants,                    "images"=>$images                    );$array = array("product"=>$productarray);$url = "https://35e0466335d7fba2b4863aa691431e26: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@your-shopify-url-goes-here/admin/api/2021-04/products.json";$curl = curl_init();curl_setopt($curl, CURLOPT_URL, $url);curl_setopt($curl, CURLOPT_HTTPHEADER, array('Content-Type: application/json'));curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "POST");curl_setopt($curl, CURLOPT_POSTFIELDS, json_encode($array));curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);$response = curl_exec ($curl);$response = json_decode($response, true);//product name link$handle[2]=$response['product']['handle'];curl_close ($curl);}
//product4$producttitle65=$obj["q65_productTitle65"];$yourasking50=$obj["q50_yourAsking50"];$productdescription68=$obj["q68_productDescription68"];if(isset($producttitle65) && !empty($producttitle65)){$whichneighborhood=$obj["q160_whichNeighborhood160"];$whichCategory=$obj["q144_whichCategory144"];$room=$obj["q164_inWhich164"];$whichneighborhoodarray=array();$whichneighborhoodarray[0]=$whichneighborhood;$producttitle=$obj["q65_productTitle65"];if($obj["q182_typeOf"] == "Sale"){$productprice=$obj["q50_yourAsking50"];$checkthe="<span>Accepted Payment Methods:</span></strong><em>  ".$checkthepayment;$whichneighborhoodarray[1]=$whichCategory;    $whichneighborhoodarray[2]=$room; $premiumListing51=$obj["q51_premiumListing51"];if($premiumListing51 != 'No thanks.' && !empty($premiumListing51)){$whichneighborhoodarray[3]='featured listings 1';  $whichneighborhoodarray[4]='featured listings 2';}}else{$productprice=0.00;$whichneighborhoodarray[1]='Give Away';$checkthe="<span>Tip (money the owner is willing to give to whoever takes this item)</span></strong><em> : ".$obj['q184_tip184']." NIS";}$Description=$obj["q68_productDescription68"];$sku4=$obj['q180_uniqueid4'];$variants=array('0' =>array("price" =>$productprice,"sku" =>'Item-'.$sku4));/*upload Imaeg*/ $images=array();if(!empty($temp_upload)){/*upload Imaeg*/   foreach ($temp_upload as $keys => $values) {if($keys == "q49_uploadA49"){$uploadimage=$values;foreach ($uploadimage as $key => $value) {$image="https://www.jotform.com/uploads/".$formID."/".$submission_id."/".$value;$bin = file_get_contents($image);$b64 = base64_encode($bin);$images[$key]=array("attachment"=>$b64,"filename"=> "Appliances.jpg");}}}}/*upload Imaeg*/ 
/*upload Photo*/
if(!empty($obj['q106_takeA106'])){
$imagescount=count($images);$typedata = explode(',', $obj['q106_takeA106']);$images[$imagescount]=array("attachment"=>$typedata[1],"filename"=> "Appliances.jpg");  }
if(!empty($obj['q104_takeAn104'])){$imagescount=count($images);$typedata = explode(',', $obj['q104_takeAn104']);$images[$imagescount]=array("attachment"=>$typedata[1],"filename"=> "Appliances.jpg");  }
if(!empty($obj['q108_takeAn108'])){$imagescount=count($images);$typedata = explode(',', $obj['q108_takeAn108']);
$images[$imagescount]=array("attachment"=>$typedata[1],"filename"=> "Appliances.jpg");  }
if(!empty($obj['q109_takeAn109'])){
$imagescount=count($images);$typedata = explode(',', $obj['q109_takeAn109']);
$images[$imagescount]=array("attachment"=>$typedata[1],"filename"=> "Appliances.jpg");  }
if(!empty($obj['q110_takeAn110'])){$imagescount=count($images);
$typedata = explode(',', $obj['q110_takeAn110']);
$images[$imagescount]=array("attachment"=>$typedata[1],"filename"=> "Appliances.jpg");  }
/*upload Photo*/$productarray=array("title" => $producttitle,                    "body_html" => $Description."<br><br> ".$mk. " <p>--------------------------------------</p><h3><span><strong>Seller Information</strong></span></h3><p><strong><span>Name: </span></strong><em>".$name."</em><em><span> </span></em></p><p><strong><span>Contact Info:</span></strong><em> (".$phonenumbercode.") ".$phonenumber." ".$email."<br></em></p><p><strong> ".$checkthe." <em><span> </span></em></em></p><p><strong><span>Item Location:</span></strong> ".$whichneighborhood." </p>".$wps,                    "template_suffix" => "requires-contact",                    "vendor" => $name,					"tags"=>$whichneighborhoodarray,                    "variants"=>$variants,                    "images"=>$images                    );
$array = array("product"=>$productarray);$url = "https://35e0466335d7fba2b4863aa691431e26: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@your-shopify-url-goes-here/admin/api/2021-04/products.json";$curl = curl_init();curl_setopt($curl, CURLOPT_URL, $url);curl_setopt($curl, CURLOPT_HTTPHEADER, array('Content-Type: application/json'));curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "POST");curl_setopt($curl, CURLOPT_POSTFIELDS, json_encode($array));curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);$response = curl_exec ($curl);$response = json_decode($response, true);//product name link$handle[3]=$response['product']['handle'];curl_close ($curl);}
//product5$producttitle67=$obj["q67_productTitle67"];$yourasking=$obj["q16_yourAsking"];$productdescription=$obj["q15_productDescription"];if(isset($producttitle67) && !empty($producttitle67)){
$whichneighborhood=$obj["q160_whichNeighborhood160"];$whichCategory=$obj["q145_whichCategory145"];$room=$obj["q165_inWhich165"];$whichneighborhoodarray=array();$whichneighborhoodarray[0]=$whichneighborhood;$producttitle=$obj["q67_productTitle67"];
if($obj["q182_typeOf"] == "Sale"){   $productprice=$obj["q16_yourAsking"];   $checkthe="<span>Accepted Payment Methods:</span></strong><em>  ".$checkthepayment;   $whichneighborhoodarray[1]=$whichCategory;       $whichneighborhoodarray[2]=$room;    $premiumListing18=$obj["q18_premiumListing18"];  if($premiumListing18 != 'No thanks.' && !empty($premiumListing18))  {    $whichneighborhoodarray[3]='featured listings 1';      $whichneighborhoodarray[4]='featured listings 2';  }}else{    $productprice=0.00;    $whichneighborhoodarray[1]='Give Away';    $checkthe="<span>Tip (money the owner is willing to give to whoever takes this item)</span></strong><em> : ".$obj['q184_tip184']." NIS";}$Description=$obj["q15_productDescription"];$sku5=$obj['q181_uniqueid5'];$variants=array('0' =>array("price" =>$productprice,"sku" =>'Item-'.$sku5));

/*upload Imaeg*/ 
$images=array();if(!empty($temp_upload)){/*upload Imaeg*/   foreach ($temp_upload as $keys => $values) {if($keys == "q17_uploadA17"){$uploadimage=$values;foreach ($uploadimage as $key => $value) {$image="https://www.jotform.com/uploads/".$formID."/".$submission_id."/".$value;$bin = file_get_contents($image);$b64 = base64_encode($bin);$images[$key]=array("attachment"=>$b64,"filename"=> "Appliances.jpg");}}}}/*upload Imaeg*/ 

/*upload Photo*/if(!empty($obj['q112_takeA112'])){$imagescount=count($images);$typedata = explode(',', $obj['q112_takeA112']);$images[$imagescount]=array("attachment"=>$typedata[1],"filename"=> "Appliances.jpg");  }
if(!empty($obj['q111_takeAn111'])){$imagescount=count($images);$typedata = explode(',', $obj['q111_takeAn111']);$images[$imagescount]=array("attachment"=>$typedata[1],"filename"=> "Appliances.jpg");  }
/*upload Photo*/
$productarray=array("title" => $producttitle,                    "body_html" => $Description."<br><br> ".$mk. " <p>--------------------------------------</p><h3><span><strong>Seller Information</strong></span></h3><p><strong><span>Name: </span></strong><em>".$name."</em><em><span> </span></em></p><p><strong><span>Contact Info:</span></strong><em> (".$phonenumbercode.") ".$phonenumber." ".$email."<br></em></p><p><strong> ".$checkthe." <em><span> </span></em></em></p><p><strong><span>Item Location:</span></strong> ".$whichneighborhood." </p>".$wps,                    "template_suffix" => "requires-contact",                     "vendor" => $name,-                    "tags"=>$whichneighborhoodarray,                    "variants"=>$variants,                    "images"=>$images                    );				
$array = array("product"=>$productarray);$url = "https://35e0466335d7fba2b4863aa691431e26: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@your-shopify-url-goes-here/admin/api/2021-04/products.json";$curl = curl_init();curl_setopt($curl, CURLOPT_URL, $url);curl_setopt($curl, CURLOPT_HTTPHEADER, array('Content-Type: application/json'));curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "POST");curl_setopt($curl, CURLOPT_POSTFIELDS, json_encode($array));curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);$response = curl_exec ($curl);$response = json_decode($response, true);
//product name link$handle[4]=$response['product']['handle'];curl_close ($curl);}}